services:
  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    build: .
    container_name: web
    ports:
      - 3000:3000
      - 24678:24678
    volumes:
      - .:/app
      - node_modules_data:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
volumes:
  db_data:
  node_modules_data:
