services:
  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    build: .
    container_name: web
    ports:
      - 3000:3000
    volumes:
      - .:/app
volumes:
  db_data:
